### Fake blog 1
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pbWEiLCJpZCI6IjY1N2Q4ZmExNWM5OTM3N2E3MjU1N2JjZSIsImlhdCI6MTcwMjczODM3OH0.i9FLCY7F3arAk6hNMNKyLUioY9aon9j3ypvibMykNxs

{
  "title": "Kokkikoulu",
  "author": "Seppo Kakkunen",
  "url": "http://kokkikoulu.com",
  "likes": 1000
}

### Fake blog 2
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pbWEiLCJpZCI6IjY1N2Q4ZmExNWM5OTM3N2E3MjU1N2JjZSIsImlhdCI6MTcwMjcyNzY1Mn0.tpx5nQEXi76UrAYaRVm5Qft0Awh01gIfb8e60yEeLpQ

{
  "title": "Juoksukoulu",
  "author": "Jaakko Jalkanen",
  "url": "http://jaakonlenkkipolku.com",
  "likes": 1
}

### Fake blog 3
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik11bWEiLCJpZCI6IjY1N2Q4OGM2MzEzNzYzOGMzMjk3YjdkNSIsImlhdCI6MTcwMjcyNzMyMX0.MeFPA3ijrFr1YoagLIvPla0sMToJK3UQnR8eaP6KK8I

{
  "title": "Life",
  "author": "Universe",
  "url": "http://fakeliving.com",
  "likes": 100
}

### Fake blog 4
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik11bWEiLCJpZCI6IjY1N2Q4OGM2MzEzNzYzOGMzMjk3YjdkNSIsImlhdCI6MTcwMjczNjM0NX0.1c6YGcm1ct0epJQ2WmnkfQomC6C8dC6PX1SKgSzDEaE

{
  "title": "Water",
  "author": "sea",
  "url": "http://fakewatersea.com",
  "likes": 8
}

### Fake blog 5
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik11bWEiLCJpZCI6IjY1N2Q4OGM2MzEzNzYzOGMzMjk3YjdkNSIsImlhdCI6MTcwMjczNjY1OX0.4quJyK-YOJFdxp-4h21fsoyRrIEEBkDSe0kieDzHgs8

{
  "title": "Air",
  "author": "wind",
  "url": "http://fakewind.com",
  "likes": 2
}
